### GET SECRET INGREDIENT.
GET http://localhost:5173/secret/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImpkZGlvIiwic3ViIjoiamRkaW8iLCJqdGkiOiJiZjk3NzI0NiIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjU5Mzc0IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzMTciLCJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJodH0RwczovL2xvY2FsaG9zdDo3MDg0Il0sIm5iZiI6MTY4MjU4NzcwNCwiZXhwIjoxNjkwNDUwMTA0LCJpYXQiOjE2ODI1ODc3MDUsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.06fZLX9eg93vEzqb1mgApnPxa-7E2-KYjNpcVEz-rq8