### Get first page of 10 products that are in stock and not discontinued
GET http://localhost:5173/api/products/

### Get first page of 10 products that are in stock and not discontinued
GET http://localhost:5173/api/products?page=3

### Get products that are out of stock but not discontinued
GET http://localhost:5173/api/products/outofstock

### Get products that are discontinued
GET http://localhost:5173/api/products/discontinued

### Get products 77
GET http://localhost:5173/api/products/77

### Get products that contain "man"
GET http://localhost:5173/api/products/man